<?php /** @var \Thesis\QuickOrder\Block\QuickOrder $block */ ?>
<?php $productSku = $block->getProductSku()?>
<button type="submit"
        title="<?= $block->escapeHtml(__('Quick Order')) ?>"
        class="btn-btn-primary"
        id="btn-btn-primary<?= /* @escapeNotVerified */ $productSku ?>"
        >
    <span>Quick Order</span>
</button>

<div class="mypopup<?= /* @escapeNotVerified */ $productSku ?>">
    <form action="<?= $block->getUrl("quickorderr/index/save") ?>"
          method="POST"
          data-mage-init='{"validation":{}}'>
        <label class="control-label required">Name</label>
            <input type="text" name="name" data-validate='{"required":true, "maxlength": 50}'>
        <label class="control-label required">Phone number</label>
            <input type="number" name="phone" data-validate='{"required":true, "maxlength": 20, "number": true}'>
        <label>Email</label>
            <input type="email" name="email" data-validate="{'maxlength': 50, 'validate-email':true }">
        <input type="hidden" name="sku" value="<?= /* @escapeNotVerified */ $productSku ?>">
        <input type="hidden" name="url" value="<?= $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true])?>">
        <input type="submit" value="Send" class="action submit primary">
    </form>
</div>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function($,modal) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Quick order',
                buttons: false
            };
            var popup = modal(options, $('.mypopup<?= /* @escapeNotVerified */ $productSku ?>'));
            $("#btn-btn-primary<?= /* @escapeNotVerified */ $productSku?>").on("click",function(){
                $('.mypopup<?= /* @escapeNotVerified */ $productSku ?>').modal('openModal');
            });
        }
    );
</script>

